### ISSUE TITLE
Add support for JavaScript exceptions

### ISSUE THREAD

**Issue by jfilak** [abrt/satyr#247]
https://github.com/humaton/abrt-nodejs

```
ReferenceError: nonexistentFunc is not defined
    at Object.<anonymous> (/home/repos/upstream/abrt-nodejs/testapp/index.js:2:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by jfilak** [comment]
```
TypeError: Cannot read property 'message' of undefined
    at Socket.<anonymous> (/home/jfilak/repos/abrt-nodejs/testapp/node_modules/abrt/index.js:16:35)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1068:10)
```

**Comment by jfilak** [comment]
Every JavaScript engine generates its own stacktrace format and the format also varies among interpreters (Node.js and Chrome - both using V8 - generate slightly different stacktraces).
